# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 17:30
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oe1Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orf_id', models.IntegerField(unique=True)),
                ('t_day', models.DateField(default=datetime.date.today)),
                ('filenames', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AddIndex(
            model_name='oe1program',
            index=models.Index(fields=['orf_id'], name='org_id_i'),
        ),
        migrations.AddIndex(
            model_name='oe1program',
            index=models.Index(fields=['t_day'], name='t_day_i'),
        ),
        migrations.AddIndex(
            model_name='oe1program',
            index=models.Index(fields=['filenames'], name='filenames_i'),
        ),
    ]
